fashionStore/urls.py
from django.urls import path,include,re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name ='fashionStore'

urlpatterns = [
    path("",views.index,name='index'),
    path("Userlogin/",views.UserLogin,name='Login'),
    path("Details/<int:product_id>/",views.details,name='details'),
    path("Category/<category_name>/",views.Category,name='Category'),
    path("Search/",views.searchPage,name="search-page"),
    path('SignUp/',views.Signup,name='signup'),
    re_path('^Email-Activation/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)$',
        views.email_confirm, name='Email-activate'),
    path("forgotpassword/",views.forgotPassword,name='forgotpassword'),
    re_path('^Password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)$',
        views.password_reset.as_view(), name='password-reset'),
    path("Signup_success/",views.Signup_success,name='Signup_success'),
    path("Customer/Account/",views.UserProfile,name="Profile"),
    path("Customer/Wishlist/",views.Wishlist,name='Wishlist'),
    path("ProductBrand/<brand_brand>/",views.productbrands,name='product-brands'),
    path("ProductSizes/<size_size>/",views.productSize,name='product-size'),
    path("ProductPrice/",views.productprice,name='product-price'),
    path("Customer/add-to-Wishlist/<int:product_id>",views.add_Wishlist,name='add-Wishlist'),
    path("Customer/Remove-from-Wishlist/<int:product_id>",views.remove_Wishlist,name='remove-Wishlist'),
    path("Customer/Order/",views.UserOrder,name='order'),
    path("Customer/RecentlyViewed/",views.RecentlyView,name='RecentlyView'),
    path("Customer/addtocart/<int:product_id>/",views.addtocart,name='add-to-cart'),
    path("Customer/account/edit",views.userDetails,name='customer-details'),
    path("Customer/Change-Password/",views.changePassword,name='changePassword'),
    path("Customer/Create-Address-Book/",views.AddressBook_create,name='Create-Address-book'),
    path("Customer/Create-Address-Book-Edit/<int:address_id>/",views.AddressBook_Edit,name='Edit-address-book'),
    path("Customer/Address/",views.userAddressBook,name="user-Address-Book"),
    path("Customer/Close-Account/",views.CloseAccount,name='close-account'),
    path("Customer/NewSeltter/",views.AddressBook,name='new-seletter'),
    path("Payment-verify/",views.verify_transaction,name='Payment-verify'),
    path("Customer/Cart/",views.ShopingCart,name='Shoping-cart'),
    path("Customer/EmptyCart/",views.EmptyCart,name='empty-cart'),
    path("Customer/Payment-Method/",views.Payment_method,name='payment-method'),
    path("Customer/Transaction-Update/<int:order_id>",views.transaction_update,name='transaction_update'),
    path("Customer/Delete/Product/<int:product_id>/",views.delete_cart_pro,name='delete-product'),
    path("Customer/Checkout/",views.Checkoutpage,name='Checkout-page'),
    path("Customer/PluQ/<int:product_id>/",views.plusQuantity,name='plusQuantity'),
    path("Customer/minusQ/<int:product_id>/",views.minusQuantity,name='minus-Quantity'),
    path("Customer/orders/details",views.order_details,name='order_details'),
    path("Logout/",views.User_logOut,name='logout'),
    path("PasswordRestDown/",views.password_down,name='password-down'),
    path('passwordchangcomplete/',views.password_reset_complete,name='password_reset_complete'),    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('FashionAdmin/', admin.site.urls),
    path('',include('fashionStore.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fashionStore/models.py
from ast import Return
import secrets
import string
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser,BaseUserManager
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.utils import timezone
from datetime import date
from django.urls import reverse
from django.contrib.auth import get_user_model

class FashionManager(BaseUserManager):
    def create_user(self, email,phoneNumber, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            phoneNumber=phoneNumber,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email,  phoneNumber, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            phoneNumber=phoneNumber,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractUser):
    sex = (("Male","Male"),("Female","Female"))
    username = models.CharField(max_length=255,unique=True,blank=True,null=True)
    email = models.EmailField(max_length=255,unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    phoneNumberRegex = RegexValidator(regex = r"^\d{8,11}$")
    Gender = models.CharField(max_length=7,choices=sex,blank=True,null=True)
    phoneNumber = models.CharField(validators = [phoneNumberRegex], max_length = 11, unique = True,blank=True,null=True)
    objects = FashionManager()
    USERNAME_FIELD ='email'
    REQUIRED_FIELDS = ['phoneNumber']
    
    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
    
class Profile(models.Model):
    User = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    Profile_pic = models.FileField("Profile Pic",upload_to='uploads/',default='uploads/default.png',validators=[FileExtensionValidator(allowed_extensions=['jpg','png'],message='Please Upload The Fellowing Image Format jpg ord png')])

    def __str__(self) -> str:
        return self.User.email






class category_products(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name
class ProductSize(models.Model):
    size = models.CharField(max_length=255,blank=True,null=True)
    
    def __str__(self):
        return self.size

class ProductBrand(models.Model):
    brand = models.CharField(max_length=255,blank=True,null=True)
    
    def __str__(self):
        return self.brand
    

class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    image = models.FileField(upload_to='product/')
    desc = models.TextField(max_length=255)
    category = models.ManyToManyField(category_products)
    sizes = models.ManyToManyField(ProductSize)
    brand = models.ManyToManyField(ProductBrand)
   

    def __str__(self) -> str:
        return self.name
    
class WhishList(models.Model):
     product = models.ForeignKey(Product,on_delete=models.SET_NULL, null=True,blank=True)
     profile= models.ForeignKey(Profile,on_delete=models.SET_NULL, null=True,blank=True)

     def __str__(self) -> str:
         return self.product.name


class order(models.Model):
    owner_user= models.ForeignKey(Profile,on_delete=models.SET_NULL, null=True,blank=True)
    order_date = models.DateField(auto_now_add=True)
    is_ordered = models.BooleanField(default=False,null=True,blank=True)
    order_id = models.CharField(max_length=20,unique=True,null=True,blank=True)
   
    @property
    def cart_total(self):
        orderitem = self.orderitem_set.all()
        total = sum([item.total_price for item in orderitem])
        return total

    @property
    def cart_item(self):
        orderitem = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitem])
        return total

    def __str__(self) -> str:
        return "%s " % self.order_id

class UsersOrderItem(models.Model):
    user_orders = models.ForeignKey(order,on_delete=models.SET_NULL,blank=True,null=True)
    image = models.FileField(upload_to='UserOrder_product/')
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    desc = models.TextField(max_length=255)
    user = models.ForeignKey(Profile,on_delete=models.SET_NULL,blank=True,null=True)

    def __str__(self) -> str:
        return self.name
 

class OrderItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,null=True,blank=True)
    order = models.ForeignKey(order,on_delete=models.SET_NULL,null=True,blank=True)
    quantity = models.IntegerField(default=1)
    date_added =models.DateField(auto_now_add=True)
    @property
    def total_price(self):
        total = self.product.price * self.quantity
        return total
    def __str__(self):
        return self.product.name
    

class AddressBook(models.Model):
    address_state = (
        (None,"Please Select State"),
        ("Delta","Delta"),
        ("Lagos","Lagos"),
        ("Abuja","Abuja"),
        ("Kano","Kano"),
        ("Rivers","Rivser"),
        ("Jos","Jos"),
        ("Sokoto","Sokoto"),
    )
    owner_user = models.ForeignKey(Profile,on_delete=models.SET_NULL, null=True,blank=True)
    order = models.ForeignKey(order,on_delete=models.SET_NULL,blank=True,null=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phoneNumberRegex = RegexValidator(regex = r"^\d{8,11}$")
    phoneNumber = models.CharField(validators = [phoneNumberRegex], max_length =11, unique=True,blank=True,null=True)
    Region = models.CharField(max_length=255,blank=True,null=True,choices=address_state)
    City= models.CharField(max_length=255)
    Delivery_address = models.CharField(max_length=255)
    Additional_information = models.CharField(max_length=255)
    zip_code = models.CharField(max_length=17)
    default_address = models.BooleanField(default=True,null=True,blank=True)

    def __str__(self):
        return self.Delivery_address
    
    class Meta:
        ordering =['Delivery_address']
    

fashionStore/forms.py
from django import forms
from . models import User,Profile,AddressBook
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import PasswordResetForm,SetPasswordForm,PasswordChangeForm


class UserCreationForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            self.fields[field_name].widget.attrs.update({'placeholder':field.label})
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name','last_name','email','phoneNumber')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserPasswordResetForm(PasswordResetForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            self.fields[field_name].widget.attrs.update({'placeholder':field.label})
    class Meta:
        model = User
        field = ('email',)

class UserSetPassword(SetPasswordForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            self.fields[field_name].widget.attrs.update({'placeholder':field.label})
    class Meta:
        model = User
        field = "__all__"

class ProfileForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            self.fields[field_name].widget.attrs.update({'placeholder':field.label})
    class Meta:
        model = Profile
        fields = ("Profile_pic",)

class UserEditForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            self.fields[field_name].widget.attrs.update({'placeholder':field.label})
    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','Gender']

class UserChangePassword(PasswordChangeForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            self.fields[field_name].widget.attrs.update({'placeholder':field.label})
    class Meta:
        model = User
        fields = "__all__"

class AddressBookForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            self.fields[field_name].widget.attrs.update({'placeholder':field.label})
    
    class Meta:
        model = AddressBook
        fields = ("first_name","last_name","phoneNumber","Region","City","Delivery_address","zip_code","Additional_information","default_address",)
        widgets ={
            'default_address':forms.CheckboxInput,
        }

fashionStore/templates/fashionStore/AddressBook_create.html
{% extends 'fashionStore/index.html' %}
{% load static %}
{% block contentWrapper %}{% endblock contentWrapper %}
{% block sortMenu %}{% endblock sortMenu %}

{% block ProductContainer %}

<div class="profile-menu">
    {% block profile-menu %}
    <a href="{% url 'fashionStore:Profile'%}"><i class="fa-solid fa-user"></i> &nbsp; My Fashion Account</a>
    <div class="userItem">
    <a href="{% url 'fashionStore:order'%}"> orders</a>
    <a href="{% url 'fashionStore:Wishlist' %}">Saved items</a>
    <a href="#">Pending Reviewed</a>
</div>
  <div class="userdetails">
    <a href="{% url 'fashionStore:customer-details' %}">Details</a>
    <a href="{% url 'fashionStore:user-Address-Book' %}">Address Book</a>
    <a href="{% url 'fashionStore:changePassword' %}">Change Password</a>
    <a href="{% url 'fashionStore:new-seletter' %}">Newseletter Preference</a>
    <a href="{% url 'fashionStore:close-account' %}">Close Account</a>

  </div>
  <a href="{% url 'fashionStore:Login' %}">Logout</a>
  {% endblock profile-menu %}
</div>
<div class="profile-content">
    {% block profile-content %}
    <div class="profile-content-title">{% block profile-content-title %} Add Address{% endblock profile-content-title %}</div>
     <div class="address-form-container">
       
        <form action="{% url 'fashionStore:Create-Address-book' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
             <!--fieldWrapper-container-->
           <div class="fieldWrapper-container">
            <div class="fieldWrapper">
                {{ form.first_name }}
                 {{ form.first_name.errors }}
            </div>

            <div class="fieldWrapper">
                {{ form.last_name }}
                {{ form.lastname.errors }}
                 
            </div>

            <div class="fieldWrapper">
                {{ form.phoneNumber }}
                {{ form.phoneNumber.errors }}
                 
            </div>

            <div class="fieldWrapper">
                {{ form.Delivery_address }}
                {{ form.Delivery_address.errors }} 
            </div>

            <div class="fieldWrapper">
                {{ form.Region }}
                {{ form.Region.errors }} 
            </div>

            <div class="fieldWrapper">
                {{ form.City }}
                {{ form.City.errors }} 
            </div>

            <div class="fieldWrapper">
                {{ form.Additional_information }}
                {{ form.Additional_information.errors }} 
            </div>

            <div class="fieldWrapper">
                {{ form.zip_code }}
                {{ form.zip_code.errors }} 
            </div>
        </div>
        <!--fieldWrapper-container-->
        <div class="fieldWrapper">
            {{ form.default_address }}
            {{ form.default_address.id_for_label }}
            {{ form.default_address.errors }} 
        </div>
            <input type="submit" value="Create Address">
        </form>
     </div>


    {% endblock profile-content %}
</div>
{% endblock ProductContainer %}

{% block paginationholder %}{% endblock paginationholder %}

fashionStore/templates/fashionStore/forgotpassword.html
{% extends 'fashionStore/signup.html' %}
{% block title %}Reset Password{% endblock title %}
{% block form-wrapper %}
<h1 style="text-align:center; text-decoration: none;"><a href="{% url 'fashionStore:index' %}" style="text-decoration: none;color: black;">FashionStore</a></h1>
<div class="form-container">
    {% block form-container %}
    <div class="signup-title">{% block signup-title %}<h3>Forgot Password</h3>{% endblock signup-title %}</div>
   <p class="fp">Can’t remember your login credentials? Enter your details below and we’ll send instructions if your account exists.</p>
        
<div class="fieldWrapper">
    <form action="{% url 'fashionStore:forgotpassword' %}" method="post">
        {% csrf_token %}
        {% for field in form  %}
        {{form}}
        <br/>
        <br/>
        {% endfor %}
        
    <input type="submit" value="Send Reset Link">
</form>

</div>   

<div class="already">
    {% block already %}
    <p>I remember my password</p>
    <a href="{% url 'fashionStore:Login' %}"><button>Login</button></a>
    {% endblock already %}
    <br/>
    <br/>
</div>

    {% endblock form-container %}
</div>


{% endblock form-wrapper %}

fashionStore/templates/fashionStore/productSizes.html
{% extends 'fashionStore/index.html' %}
{% load static %}
{% block contentWrapper %}{% endblock contentWrapper %}
{% block ProductContainer %}

<div class="search-category">
     <!--search cat holder-->
    {% if cats %}
    {% for cats in cats  %}
    <a href="{% url 'fashionStore:Category' cats.name %}">{{cats.name|title}}</a>
    {% endfor %}
    {% endif %}
    <!--search cat holder-->
    <div class="search-header">
        <p>Brand</p>
        {% if brand %}
        {% for brand in brand %}
        <a href="{% url 'fashionStore:product-brands' brand.brand %}"><button id="brand-btn"></button> &nbsp;<label for="Sizes">{{brand.brand}}</label></a>
        {% endfor %}
        {% endif %}
    </div>
    
    <div class="search-header">
        <p>Price(&#8358;)</p>
        <form action="{% url 'fashionStore:product-price' %}" method="get">
           {% csrf_token %}
           
           <input type="number" name="low" id="low">- <input type="number" name="hi" id="high">
          <br> 
          <input type="submit" value="Apply">
        </form>
    </div>

    <div class="search-header">
        <p>Size</p>
        {% if size %}
        {% for sizes in size %}
        <a href="{% url 'fashionStore:product-size' sizes.size %}"><button id="size-btn"></button> &nbsp;<label for="Sizes">{{sizes.size}}</label></a>
        {% endfor %}
        {% endif %}

    </div>
</div>
<!--search-cate-->


<div class="search-product-data">
    <div class="search-p-d-menuwrapper">
    <div class="brands"><p>Size:{{product_size.size}}</p></div>
    </div>
    {% if product_size.product_set.all.count %}
    <div class="total-found"><p>{{product_size.product_set.all.count}} products Found</p></div>
    {% else %}
    <div class="total-found"><p> 0 products Found</p></div>
    {% endif %}

    <div class="search-product-holder">

        {% if product_size.product_set.all %}
    {% for products in product_size.product_set.all  %}
   <a href="{% url 'fashionStore:details' products.id %}" style="text-decoration:none;color:tomato;"> <div class="Productholder">
        <img src="{{products.image.url}}">
        <p style="font-weight:bold;">{{products.name}}</p>
        <p>&#8358;{{products.price}}</p>
        <p>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star"></span>
        <span class="fa fa-star"></span>
        </p>
        <div class="cartbtn">
            <a href="{% url 'fashionStore:add-Wishlist' products.id %}" style="font-size:20px; float:right; text-decoration:none; padding-top:5px;"><i class="fa-regular fa-heart" style="font-size:20px;"></i> &nbsp;</a>
            <form action="{% url 'fashionStore:add-to-cart' products.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Add To Cart">
            </form>
        </div>
    </a>
    </div>
    {% endfor %}


    {% endif %}


    </div>
    





</div>

{% endblock ProductContainer %}

fashionStore/templates/fashionStore/productprice.html
{% extends 'fashionStore/index.html' %}
{% load static %}
{% block contentWrapper %}{% endblock contentWrapper %}
{% block ProductContainer %}

<div class="search-category">
     <!--search cat holder-->
    {% if cats %}
    {% for cats in cats  %}
    <a href="{% url 'fashionStore:Category' cats.name %}">{{cats.name|title}}</a>
    {% endfor %}
    {% endif %}
    <!--search cat holder-->
    <div class="search-header">
        <p>Brand</p>
        {% if brand %}
        {% for brand in brand %}
        <a href="{% url 'fashionStore:product-brands' brand.brand %}"><button id="brand-btn"></button> &nbsp;<label for="Sizes">{{brand.brand}}</label></a>
        {% endfor %}
        {% endif %}
    </div>
    
    <div class="search-header">
        <p>Price(&#8358;)</p>
        <form action="{% url 'fashionStore:product-price' %}" method="get">
           {% csrf_token %}
           
          <input type="number" name="low" id="low">- <input type="number" name="hi" id="high">
          <br> 
          <input type="submit" value="Apply">
        </form>
    </div>

    <div class="search-header">
        <p>Size</p>
        {% if size %}
        {% for sizes in size %}
        <a href="{% url 'fashionStore:product-size' sizes.size %}"><button id="size-btn"></button> &nbsp;<label for="Sizes">{{sizes.size}}</label></a>
        {% endfor %}
        {% endif %}

    </div>
</div>
<!--search-cate-->


<div class="search-product-data">
    <div class="search-p-d-menuwrapper">
    <div class="brands"><p>Price:{{category1.name}}</p></div>

    
    </div>
    {% if price %}
    <div class="total-found"><p>{{price|length}} products Found</p></div>
    {% else %}
    <div class="total-found"><p> 0 products Found</p></div>
    {% endif %}

    <div class="search-product-holder">

        {% if price %}
    {% for products in price  %}
   <a href="{% url 'fashionStore:details' products.id %}" style="text-decoration:none;color:tomato;"> <div class="Productholder">
        <img src="{{products.image.url}}">
        <p style="font-weight:bold;">{{products.name}}</p>
        <p>&#8358;{{products.price}}</p>
        <p>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star"></span>
        <span class="fa fa-star"></span>
        </p>
        <div class="cartbtn">
            <a href="{% url 'fashionStore:add-Wishlist' products.id %}" style="font-size:20px; float:right; text-decoration:none; padding-top:5px;"><i class="fa-regular fa-heart" style="font-size:20px;"></i> &nbsp;</a>
            <form action="{% url 'fashionStore:add-to-cart' products.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Add To Cart">
            </form>
        </div>
    </a>
    </div>
    {% endfor %}
    {% endif %}
    </div>
</div>
{% endblock ProductContainer %}

<div class="paginationholder">
    {% block paginationholder %}
        <div class="pagination">
            {% if category.has_previous  %}
            <a href="?page={{ category.previous_page_number}}">&nbsp;&laquo;</a>
            {% endif %}
            {% for range in category.paginator.page_range %}
            <a href="?page={{range}}">{{range}}</a>
            {% endfor %}
            
            {% if product.has_next  %}
            <a href="?page={{  category.next_page_number}}">&nbsp;&raquo;</a>
            <a href="?page={{  category.paginator.num_pages }}">last&nbsp; &raquo;</a>
            {% endif %}
      </div>
      {% endblock paginationholder %}
</div>

fashionStore/templates/fashionStore/search_result.html
{% extends 'fashionStore/index.html' %}
{% load static %}
{% block contentWrapper %}{% endblock contentWrapper %}
{% block ProductContainer %}

<div class="search-category">
     <!--search cat holder-->
    {% if cats %}
    {% for cats in cats  %}
    <a href="{% url 'fashionStore:Category' cats.name %}">{{cats.name|title}}</a>
    {% endfor %}
    {% endif %}
    <!--search cat holder-->
    <div class="search-header">
        <p>Brand</p>
        {% if brand %}
        {% for brand in brand %}
        <a href="{% url 'fashionStore:product-brands' brand.brand %}"><button id="brand-btn"></button> &nbsp;<label for="Sizes">{{brand.brand}}</label></a>
        {% endfor %}
        {% endif %}
    </div>
    
    <div class="search-header">
        <p>Price(&#8358;)</p>
        <form action="{% url 'fashionStore:product-price' %}" method="get">
           {% csrf_token %}
           
           <input type="number" name="low" id="low">- <input type="number" name="hi" id="high">
          <br> 
          <input type="submit" value="Apply">
        </form>
    </div>

    <div class="search-header">
        <p>Size</p>
        {% if size %}
        {% for sizes in size %}
        <a href="{% url 'fashionStore:product-size' sizes.size %}"><button id="size-btn"></button> &nbsp;<label for="Sizes">{{sizes.size}}</label></a>
        {% endfor %}
        {% endif %}

    </div>
</div>
<!--search-cate-->


<div class="search-product-data">
    <div class="search-p-d-menuwrapper">
    <div class="brands"><p>FashionStore online Shopping</p></div>

    <div class="sort-s"><button>Sort by:</button></div>
    </div>
    {% if result.all.count %}
    <div class="total-found"><p>{{result.all.count}} products Found</p></div>
    {% else %}
    <div class="total-found"><p> 0 products Found</p></div>
    {% endif %}

    <div class="search-product-holder">

        {% if result %}
    {% for products in result  %}
   <a href="{% url 'fashionStore:details' products.id %}" style="text-decoration:none;color:tomato;"> <div class="Productholder">
        <img src="{{products.image.url}}">
        <p style="font-weight:bold;">{{products.name}}</p>
        <p>&#8358;{{products.price}}</p>
        <p>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star"></span>
        <span class="fa fa-star"></span>
        </p>
        <div class="cartbtn">
            <a href="{% url 'fashionStore:add-Wishlist' products.id %}" style="font-size:20px; float:right; text-decoration:none; padding-top:5px;"><i class="fa-regular fa-heart" style="font-size:20px;"></i> &nbsp;</a>
            <form action="{% url 'fashionStore:add-to-cart' products.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Add To Cart">
            </form>
        </div>
    </a>
    </div>
    {% endfor %}
    {% else %}


    {% endif %}


    </div>
    





</div>

{% endblock ProductContainer %}